name: 'data_pipeline'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  kafka_broker: 'broker:29092'
  kafka_schema_registry: 'http://schema-registry:8081'
  kafka_topic: 'postgres.public.emission'

models:
  data_pipeline:
    staging:
      +materialized: view
      snowflake_warehouse: TEST_WAREHOUSE

    marts:
      +materialized: table
      snowflake_warehouse: TEST_WAREHOUSE
